site_name: 网安在线考研知识库
site_url: https://mcxiaoxiao.github.io/HIT837-Book-of-Answer
nav:
  - 首页: 
    - Getting Started: index.md
    - 哈尔滨工业大学资源索引: hit837.md
  - 自命题索引: 真题.md
  - 初试知识库:
    - 哈工大837:
      - 前言: hit837bookofanswer.md
      - 信息安全基础: 
        - 前言: 信安基础/0.md
        - 信息安全的基本概念:
          - OSI TCP/IP 信息安全体系架构 ISO 7498-2 CIA PDRR PD2R: 信安基础/1.md
          - 容错与容灾的概念及主要技术方法: 信安基础/2.md
        - 密码学基础:
          - 古典替换密码 移位密码 凯撒密码 乘数密码 仿射密码 多表代替 维吉尼亚密码: 信安基础/3.md
          - 现代密码系统 对称密钥、公钥密码思想、密码体制、密码系统: 信安基础/4.md
          - 密码分析与攻击模型: 信安基础/5.md
          - DES 对称数据加密标准：算法结构、特点与加密模式: 信安基础/6.md
          - DH Diffie-Hellman 对称密钥交换协议: 信安基础/7.md
          - RSA 公钥密码 单向性 陷门性 单向陷门函数: 信安基础/8.md
          - HASH 消息摘要 散列函数 单向性 无碰撞性: 信安基础/9.md
        - 身份认证与访问控制:
          - 身份认证 2FA OTP: 信安基础/10.md
          - 三种消息认证函数 MAC 消息认证码 消息编码 禁用/许用序列 MD5 SHA-1 SHA-256: 信安基础/11.md
          - 数字签名 定义 原理 应用过程: 信安基础/12.md
          - Windows 网络认证 域登录 winlogon netlogon: 信安基础/13.md
          - Windows 安全子系统 域访问控制 网络管理 活动目录 AD 组策略 GP 安全架构 访问控制模块 LSA SRM DACL ACE SACL: 信安基础/14.md
          - 公开密钥 挑战-应答 认证协议 Needham–Schroeder 单向、双向认证的公钥协议: 信安基础/15.md
          - 对称密钥 挑战-应答 认证协议: 信安基础/16.md
          - 对称密钥 Needham-Schroeder 第三方认证协议 重放攻击漏洞: 信安基础/17.md
          - 对称密钥 Kerberos 认证协议 单点失效问题: 信安基础/18.md
          - PKI 公开密钥基础设施 CA 数字证书 原理和使用证书链 X.509: 信安基础/19.md
          - 访问控制策略 访问策略原则 DAC 自主访问控制 MAC 强制访问控制 RBAC 基于角色的访问控制: 信安基础/20.md
        - 计算机病毒与网络入侵: 信安基础/21.md
        - 防火墙入侵检测安全传输协议:
          - FW 防火墙主要技术 体系结构 ACL 动态/静态包过滤 NAT VPN DMZ: 信安基础/22.md 
          - Linux Netfilter / Iptables 的工作原理 hook 钩子函数指针链: 信安基础/23.md 
          - IDS 入侵检测系统 入侵诱骗: 信安基础/24.md
          - NIDS 基于网络 HIDS 基于主机 优缺点: 信安基础/25.md
          - IDES CIDF 入侵检测系统模型 Snort 三维链表: 信安基础/26.md
          - 应用层防火墙能否完全取代入侵检测系统 IDS?: 信安基础/27.md
          - IPSEC 网络层安全协议 体系结构 基本要件 建立安全关联 SA IKE Internet 密钥交换协议 SPI SAD SPD 抗重放攻击机制 HMAC: 信安基础/28.md
          - IPSEC AH ESP 传输模式 隧道模式 完整性认证: 信安基础/29.md
          - SSL 安全套接字层协议 传输层安全协议的四个协议: 信安基础/30.md
          - HTTPS 建立 作用: 信安基础/31.md
          - SET 安全电子交易协议 DS 双重签名 电子信封: 信安基础/32.md
          - SET 与 SSL 比较: 信安基础/33.md
        - 安全风险管理与法律法规:
          - CC 与 BS7799 的定义 GB17895-1999 国家信息安全标准体系 法律法规道德规范: 信安基础/34.md
          - 风险管理 风险评估 风险控制: 信安基础/35.md
          - 内容安全 数字版权: 信安基础/36.md
          - DRM 结构原理: 信安基础/37.md
          - 数字水印的工作原理: 信安基础/38.md
      - 网络安全基础:
        - 前言: 网安基础/0.md
        - 网络攻击: 
          - 网络各层协议的缺陷、脆弱性、攻击: 网安基础/1.md
          - 网络入侵 拒绝服务攻击 缓冲区溢出 电子邮件炸弹: 网安基础/2.md
          - 剧毒包拒绝服务攻击（Ping of Death、碎片攻击/ Tear Drop Land 攻击 Chargen 循环攻击）: 网安基础/6.md
          - 风暴型拒绝服务攻击（TCP SYN Flood、HTTP CC、IP欺骗 & ICMP Ping Floods & Smurf）: 网安基础/7.md
          - 重定向拒绝服务攻击（ARP欺骗 中间人攻击）: 网安基础/8.md
          - 重定向拒绝服务攻击（DNS欺骗 监听式主机欺骗 DNS服务器污染 中间人攻击）: 网安基础/9.md
          - 反射型拒绝服务攻击（放大攻击 NTP DNS Chargen）: 网安基础/10.md
          - 直接型拒绝服务攻击（僵尸网络 DDoS）: 网安基础/11.md
          - DHCP欺骗 DHCP流程: 网安基础/12.md
          - WEB脆弱性 网站攻击技术: 网安基础/15.md
          - 堆 栈 BSS 注入攻击 ROP攻击 溢出原理 防护: 网安基础/17.md
        - 网络数据获取: 
          - 网卡的工作原理 DMA机制 Sniffer 包捕获机制: 网安基础/3.md
          - 网络数据包捕获机制 BPF模型: 网安基础/4.md
          - 数据链路层编程接口 Libcap wincap 数据采集: 网安基础/5.md
        - 网络扫描技术: 网安基础/14.md
        - 入侵检测: 
          - 网络监听的检测: 网安基础/13.md
          - WEB应用防火墙 WAF: 网安基础/16.md
        - 典型模式匹配算法: 网安基础/19.md
        - 典型分类聚类算法: 网安基础/18.md

      - 计算机网络: 
        - 前言: 计算机网络/0.md
        - 计算机网络体系结构的概念: 
          - 常见服务 中英文对照 端口 层: 计算机网络/18.md
          - 端到端原则: 计算机网络/15.md
        - 应用层: 
          - Ping 分组网间探测 Traceroute 的作⽤及其原理: 计算机网络/1.md
          - P2P（Peer-to-Peer）BitTorrent BT协议: 计算机网络/14.md
          - DNS（域名系统） 递归查询/迭代查询: 计算机网络/17.md
        - 传输层: 
          - TCP（传输控制协议）结构: 计算机网络/3.md
          - TCP 可靠传输 慢开始 网络超时 拥塞避免 冗余确认 重复确认 快重传 快恢复 的原理机制: 计算机网络/5.md
          - TCP 流量控制 接收窗口的原理: 计算机网络/6.md
          - TCP 三次握手 四次挥手: 计算机网络/7.md
          - UDP（用户数据报协议）结构: 计算机网络/4.md
        - Socket编程: 计算机网络/8.md
        - 网络层: 
          - IP（互联网协议）: 计算机网络/9.md
          - 子网划分 CIDR 子网掩码: 计算机网络/16.md
          - ARP（地址解析协议）地址含义 原理: 计算机网络/10.md
          - RIP（路由信息协议）距离向量路由算法 DV算法 BF方程 Bellman-Ford: 计算机网络/11.md
          - OSPF（开放式最短路径优先）链路状态路由算法 LS算法 洪泛法 Dijkstra: 计算机网络/12.md
          - BGP （边界网关协议）路径向量路由算法: 计算机网络/13.md

        - 链路层: 计算机网络/2.md

  - 复试知识库: 
    - 哈工大计算学部: 
      - 前言: 复试/intro.md
      - 历年机试真题: 复试/test.md
  - 开放论坛: https://github.com/mcxiaoxiao/wangan.online/discussions



theme:
  name: material
  logo: logo.png
  favicon: logo.png
  language: zh
  features:
    - navigation.tabs
    - search.suggestions
    - search.highlight
    - navigation.top
    - content.tooltips
    - content.footnote.tooltips
    - navigation.footer
    - content.code.copy
    - content.code.select

  icon:
    admonition:
      warning: material/plus-circle-multiple-outline

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


repo_url: https://github.com/mcxiaoxiao/wangan.online
repo_name: 编辑
copyright: Copyright &copy; <a href="https://github.com/mcxiaoxiao/wangan.online" target="_blank">wangan.online</a> 网安在线考研知识库 🎓 <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script> 本页至今已助力 <span id="busuanzi_value_page_pv"></span> 次有意义的探索，距离实现“消灭一切网安考研信息差”的愿景更进一步！ <script async src="https://www.googletagmanager.com/gtag/js?id=G-PXE4WWSR48"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-PXE4WWSR48'); </script>   </br>  <img width="131" height="42" alt="image" src="https://github.com/user-attachments/assets/241fb14e-f968-4a31-a256-06037ba057ec" />


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mcxiaoxiao/wangan.online
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=a4cUnzEAAAAJ

plugins:
  - search:
      lang: zh
      jieba_dict: dict.txt.big
  - tags

markdown_extensions: 
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details


extra:
  generator: false

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js