site_name: 网安在线考研知识库
site_url: https://mcxiaoxiao.github.io/HIT837-Book-of-Answer
nav:
  - 首页: 
    - Getting Started: index.md
    - 哈尔滨工业大学: hit837.md
  - 真题索引: 真题.md
  - 初试资料:
    - 哈工大837:
      - 前言: hit837bookofanswer.md
      - 信息安全基础: 
        - 前言: 信安基础/0.md
        - 信息安全的基本概念:
          - OSI TCP/IP 信息安全体系架构 ISO 7498-2 CIA PDRR PD2R: 信安基础/1.md
          - 容错与容灾的概念及主要技术方法: 信安基础/2.md
          - 古典替换密码 移位密码 凯撒密码 乘数密码 仿射密码 多表代替 维吉尼亚密码: 信安基础/3.md
          - 现代密码系统 对称密钥、公钥密码思想、密码体制、密码系统: 信安基础/4.md
          - 密码分析与攻击模型: 信安基础/5.md
          - DES 对称数据加密标准：算法结构、特点与加密模式: 信安基础/6.md
          - DH Diffie-Hellman 对称密钥交换协议: 信安基础/7.md
          - RSA 公钥密码 单向性 陷门性 单向陷门函数: 信安基础/8.md
          - HASH 消息摘要 散列函数 单向性 无碰撞性: 信安基础/9.md
          - 身份认证 2FA OTP: 信安基础/10.md
          - 三种消息认证函数 MAC 消息认证码 消息编码 禁用/许用序列 MD5 SHA-1 SHA-256: 信安基础/11.md
          - 数字签名 定义 原理 应用过程: 信安基础/12.md
          - Windows 网络认证 域登录 winlogon netlogon: 信安基础/13.md
          - Windows 安全子系统 域访问控制 网络管理 活动目录 AD 组策略 GP 安全架构 访问控制模块 LSA SRM DACL ACE SACL: 信安基础/14.md
          - 公开密钥 挑战-应答 认证协议 Needham–Schroeder 单向、双向认证的公钥协议: 信安基础/15.md
          - 对称密钥 挑战-应答 认证协议: 信安基础/16.md
          - 对称密钥 Needham-Schroeder 第三方认证协议 重放攻击漏洞: 信安基础/17.md
          - 对称密钥 Kerberos 认证协议 单点失效问题: 信安基础/18.md
          - PKI 公开密钥基础设施 CA 数字证书 原理和使用证书链 X.509: 信安基础/19.md
          - 访问控制策略 访问策略原则 DAC 自主访问控制 MAC 强制访问控制 RBAC 基于角色的访问控制: 信安基础/20.md
          - 传统病毒、蠕虫、木马的结构原理 隐藏技术 API劫持 CIH 尼姆达 Nimda Redcode 端口复用 反弹端口: 信安基础/21.md
        - 密码学基础:
          - OSI: 信安基础/1.md
        - 身份认证与访问控制:
          - OSI: 信安基础/1.md
        - 计算机病毒与网络入侵:
          - OSI: 信安基础/1.md
        - 防火墙入侵检测安全传输协议:
          - OSI: 信安基础/1.md
        - 安全风险管理与法律法规:
          - OSI: 信安基础/1.md
      - 网络安全基础:
        - 前言: 网安基础/0.md
        - 网络攻击: 网安基础/1.md
        - 网络数据获取: 网安基础/2.md
        - 网络扫描技术: 网安基础/3.md
        - 入侵检测: 网安基础/4.md
        - 典型模式匹配算法: 网安基础/5.md
        - 典型分类聚类算法: 网安基础/6.md
        - 身份认证技术: 网安基础/7.md
      - 计算机网络: 
        - 前言: 计算机网络/0.md
        - 计算机网络体系结构的概念: 计算机网络/1.md
        - 应用层: 计算机网络/2.md
        - 传输层: 计算机网络/3.md
        - socket编程: 计算机网络/4.md
        - 网络层: 计算机网络/5.md
        - 链路层: 计算机网络/6.md
  - 复试资料: 
    - 哈工大计算学部: 复试/0.md
  - 开放论坛: https://github.com/mcxiaoxiao/HIT837-Book-of-Answer/discussions



theme:
  name: material
  logo: logo.png
  favicon: logo.png
  language: zh
  features:
    - navigation.tabs
    - search.suggestions
    - search.highlight
    - navigation.top
    - content.tooltips
    - content.footnote.tooltips
    - navigation.footer

  icon:
    admonition:
      warning: material/plus-circle-multiple-outline

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


repo_url: https://github.com/mcxiaoxiao/HIT837-Book-of-Answer/tree/page
repo_name: 编辑
copyright: Copyright &copy; <a href="https://github.com/mcxiaoxiao/HIT837-Book-of-Answer" target="_blank">HIT837-Book-of-Answer</a> 网安在线考研知识库 🎓 <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script> 本页至今已助力 <span id="busuanzi_value_page_pv"></span> 次有意义的探索，距离实现消灭一切网安备考信息差的愿景更进一步！ <script async src="https://www.googletagmanager.com/gtag/js?id=G-PXE4WWSR48"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-PXE4WWSR48'); </script>   </br>  <img width="131" height="42" alt="image" src="https://github.com/user-attachments/assets/241fb14e-f968-4a31-a256-06037ba057ec" />


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mcxiaoxiao/HIT837-Book-of-Answer
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=a4cUnzEAAAAJ

plugins:
  - search:
      lang: zh
      jieba_dict: dict.txt.big
  - tags
  - meta-descriptions:
      enable_checks: true
      min_length: 20      # Minimum character count
      max_length: 500     # Maximum (SEO recommended)
      trim: true          # Auto-trim if exceeded

markdown_extensions: 
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details


extra:
  generator: false

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js